// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import (
    "fmt"
	"os"
    "github.com/swaggo/swag"
    "golang-api-lite/utility"
)

func init() {
    var docString, err = os.ReadFile("docs/swagger.json")
    var config = utility.GetConfig()
    var host = utility.GetActiveEnv(config, true)

	if err != nil {
		fmt.Print(err)
	}

	var docTemplate = string(docString)

    // SwaggerInfo holds exported Swagger Info so clients can modify it
    var SwaggerInfo = swag.Spec{
        Version:          "2.0.1",
        Host:             host,
        BasePath:         "",
        Schemes:          []string{},
        Title:            "",
        Description:      "",
        InfoInstanceName: "swagger",
        SwaggerTemplate:  docTemplate,
        LeftDelim:        "{{",
        RightDelim:       "}}",
}

    swag.Register(SwaggerInfo.InstanceName(), &SwaggerInfo)
}
